version: "3"
services:
  redis:
    image: redis
    container_name: redis
    environment:
      - discovery.type=single-node
    ports:
      - 6379:6379
  papaye:
    build: ./
    command: node init.js
    depends_on:
      - redis
    ports:
      - 80:8080
      - 3333:3333
      - 3256:3256
    volumes:
        - ./:/opt/papaye/
        - /opt/papaye/node_modules

volumes:
    papaye:
      driver: local