version: "3"
services:
  papaye:
    build: ./
    command: node init.js
    ports:
      - 81:8080
      - 3333:3333
    volumes:
        - ./:/opt/papaye/
        - /opt/papaye/node_modules

volumes:
    papaye:
      driver: local